### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by slowkow** [klarman-cell-observatory/demuxEM#6]
Please consider adding tests:

- to verify that demuxEM is compatible with pegasusio
- to verify that demuxEM works with a matrix generated by cumulus_adt (this bug is still unresolved)

This will prevent future bugs like #3

**Comment by bli25broad** [comment]
@slowkow We have tested that demuxEM is compatible with pegasusio and works with cumulus_adt.  For the issue you mentioned, I have reopened your pull request. Please share with us an example dataset triggering the bug.

I'll close this issue.
